UNICODE_ENABLE  = yes # Unicode
RGBLIGHT_ENABLE = yes

# Trim Code
LTO_ENABLE           = yes
SPACE_CADET_ENABLE   = no
GRAVE_ESC_ENABLE     = no
TAP_DANCE_ENABLE     = no
NO_USB_STARTUP_CHECK = yes
BOOTMAGIC_ENABLE     = no
